<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Emgu.CV" Version="4.13.0.5924" />
    <PackageReference Include="Emgu.CV.Bitmap" Version="4.13.0.5924" />
    <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="SkiaSharp" Version="4.148.0" />
    <PackageReference Include="Standard.Licensing" Version="1.3.0" />
  </ItemGroup>

</Project>
